apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-website
  name: nginx-website-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 60
      periodSeconds: 120
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 60
      periodSeconds: 120
