#example y los puertos se pueden sustuir por etiquetas y puertos a convenir"

apiVersion: v1
kind: Service
metadata:
  name: "example"
spec:
  type: NodePort
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 30000
  selector:
    role: "example"

